#!/usr/bin/env bash
# Pull Strictly Jayers hub secrets from GCP Secret Manager into apps/web/.env.local
# (and write .env.espn for sj sync).
#
# Prerequisites:
#   - gcloud authenticated (Cloud Shell, or `gcloud auth login` locally)
#   - permission: roles/secretmanager.secretAccessor on the secrets
#
# Usage:
#   ./scripts/pull-hub-secrets.sh
#   GCP_PROJECT=fantasy-sports-analytics ./scripts/pull-hub-secrets.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT="${GCP_PROJECT:-fantasy-sports-analytics}"
OUT="${ROOT}/apps/web/.env.local"
ESPN_OUT="${ROOT}/.env.espn"

access() {
  local name="$1"
  gcloud secrets versions access latest --secret="${name}" --project="${PROJECT}"
}

# Write KEY=value with shell-safe single quotes.
env_line() {
  local key="$1"
  local value="$2"
  python3 -c 'import sys; k,v=sys.argv[1],sys.argv[2]; print(f"{k}={v!r}")' "${key}" "${value}"
}

echo "Reading secrets from project ${PROJECT}..."

AUTH_SECRET="$(access sj-auth-secret)"
AUTH_GOOGLE_ID="$(access sj-auth-google-id)"
AUTH_GOOGLE_SECRET="$(access sj-auth-google-secret)"
ALLOWED_EMAILS="$(access sj-allowed-emails)"

if [[ "${AUTH_SECRET}" == "REPLACE_ME" || "${AUTH_GOOGLE_ID}" == "REPLACE_ME" ]]; then
  echo "warning: one or more auth secrets still have the REPLACE_ME placeholder." >&2
  echo "Populate them in Cloud Shell before relying on Google sign-in." >&2
fi

umask 077
{
  echo "# Generated by scripts/pull-hub-secrets.sh — do not commit"
  env_line AUTH_SECRET "${AUTH_SECRET}"
  env_line AUTH_GOOGLE_ID "${AUTH_GOOGLE_ID}"
  env_line AUTH_GOOGLE_SECRET "${AUTH_GOOGLE_SECRET}"
  env_line ALLOWED_EMAILS "${ALLOWED_EMAILS}"
  echo "AUTH_DEV_BYPASS=0"
  echo "SJ_RECAP_MODEL=gpt-5.6-luna"
} >"${OUT}"

echo "Wrote ${OUT}"

if OPENAI_API_KEY="$(access openai-api-key 2>/dev/null)"; then
  if [[ "${OPENAI_API_KEY}" != "REPLACE_ME" && -n "${OPENAI_API_KEY}" ]]; then
    env_line OPENAI_API_KEY "${OPENAI_API_KEY}" >>"${OUT}"
    echo "Appended OPENAI_API_KEY to ${OUT}"
  else
    echo "openai-api-key still REPLACE_ME — skipped OPENAI_API_KEY"
  fi
else
  echo "openai-api-key not readable — skipped OPENAI_API_KEY"
fi

if ESPN_S2="$(access sj-espn-s2 2>/dev/null)" && ESPN_SWID="$(access sj-espn-swid 2>/dev/null)"; then
  if [[ "${ESPN_S2}" != "REPLACE_ME" && "${ESPN_SWID}" != "REPLACE_ME" ]]; then
    {
      echo "# Generated by scripts/pull-hub-secrets.sh — do not commit"
      echo "# Usage: source .env.espn && sj sync --current-only"
      env_line ESPN_S2 "${ESPN_S2}" | sed 's/^/export /'
      env_line ESPN_SWID "${ESPN_SWID}" | sed 's/^/export /'
    } >"${ESPN_OUT}"
    chmod 600 "${ESPN_OUT}"
    echo "Wrote ${ESPN_OUT}"
  else
    echo "ESPN secrets still REPLACE_ME — skipped .env.espn"
  fi
else
  echo "ESPN secrets not readable — skipped .env.espn"
fi

echo "Done."
