"""Generate realistic-scale synthetic snapshots for local development.

The committed fixtures in ``fixtures/sj/`` stay small (3–4 teams) and on the
schema_version 1 monolith layout so dual-read stays covered, but they are
regenerated from this module via ``sj regenerate-fixtures`` (roadmap 2.5) so
they cannot drift from the live serializer. They still hide problems that only
show up at real scale — unpaginated tables, wide-table layout on mobile, page
weight, and multi-season navigation — which is what ``sj seed`` is for.

This module fills that gap. It fabricates espn-api-shaped objects and runs them
through the *real* serializer (:func:`sj.sync.build_snapshot`) and the *real*
store, so seeded output cannot drift from what a live ESPN sync produces. When
``serialize.py`` changes, seeded data changes with it.

Seeding is deterministic per league-season, so a given registry produces
byte-identical output on every machine and every run.

Synthetic data is written to a local directory only -- never to Cloud Storage --
and the target directory gets a ``SYNTHETIC.txt`` marker so seeded snapshots are
never mistaken for real league history.
"""

from __future__ import annotations

import random
from pathlib import Path
from typing import Any

from sj.registry import LeagueSpec, load_registry
from sj.store import DEFAULT_STORE_DIR, INDEX_NAME, FileStore
from sj.sync import build_snapshot

DEFAULT_TEAM_COUNT = 12

MARKER_NAME = "SYNTHETIC.txt"
MARKER_TEXT = """\
This directory holds SYNTHETIC snapshots generated by `sj seed`.

The data is fabricated for local development and UI testing. Team names, owner
names, players, and stats are not real. Delete this directory and run
`sj sync` with ESPN credentials to replace it with real league data.
"""

_FIRST_NAMES = (
    "James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph",
    "Thomas", "Charles", "Christopher", "Daniel", "Matthew", "Anthony", "Mark", "Paul",
    "Steven", "Andrew", "Kenneth", "Joshua", "Kevin", "Brian", "George", "Timothy",
    "Ronald", "Jason", "Edward", "Jeffrey", "Ryan", "Jacob", "Gary", "Nicholas", "Eric",
    "Jonathan", "Stephen", "Justin", "Scott", "Brandon", "Benjamin", "Samuel", "Gregory",
    "Patrick", "Alexander", "Jack", "Dennis", "Tyler", "Aaron", "Jose", "Adam", "Nathan",
    "Henry", "Zachary", "Douglas", "Peter", "Kyle", "Noah", "Ethan", "Jeremy", "Walter",
    "Christian", "Keith", "Roger", "Terry", "Austin", "Sean", "Carl", "Dylan", "Harold",
    "Jordan", "Jesse", "Bryan", "Lawrence", "Arthur", "Gabriel", "Bruce", "Logan", "Alan",
    "Juan", "Elijah", "Albert", "Wayne", "Randy", "Mason", "Roy", "Ralph", "Bobby",
    "Russell", "Bradley", "Philip", "Eugene",
)

_LAST_NAMES = (
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White",
    "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker", "Young",
    "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green",
    "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter",
    "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker", "Cruz",
    "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales", "Murphy", "Cook",
    "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson", "Bailey", "Reed",
    "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks",
    "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes", "Price",
    "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", "Ross", "Foster",
    "Jimenez",
)

_FOOTBALL_TEAM_NAMES = (
    "Gridiron Goons",
    "Turf Titans",
    "End Zone Enforcers",
    "Hail Mary Heroes",
    "Blitz Brigade",
    "Pocket Pirates",
    "Red Zone Rebels",
    "Shotgun Syndicate",
    "Play Action Pros",
    "Audible Assassins",
    "Two Minute Warning",
    "Pigskin Punishers",
    "Screen Pass Scoundrels",
    "Fourth Down Fiends",
)

_BASEBALL_TEAM_NAMES = (
    "Diamond Dogs",
    "Bat Flip Bandits",
    "Curveball Crew",
    "Grand Slam Gang",
    "Bullpen Bandits",
    "Cleanup Crew",
    "Squeeze Play Squad",
    "Warning Track Warriors",
    "Knuckleball Kings",
    "Dinger Dynasty",
    "Rally Cap Renegades",
    "Golden Sombreros",
    "Infield Flies",
    "Walk Off Warlords",
)

_NFL_TEAMS = (
    "ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL", "DEN", "DET", "GB",
    "HOU", "IND", "JAX", "KC", "LAC", "LAR", "LV", "MIA", "MIN", "NE", "NO", "NYG", "NYJ",
    "PHI", "PIT", "SEA", "SF", "TB", "TEN", "WSH",
)

_MLB_TEAMS = (
    "ARI", "ATL", "BAL", "BOS", "CHC", "CWS", "CIN", "CLE", "COL", "DET", "HOU", "KC",
    "LAA", "LAD", "MIA", "MIL", "MIN", "NYM", "NYY", "OAK", "PHI", "PIT", "SD", "SF",
    "SEA", "STL", "TB", "TEX", "TOR", "WSH",
)

# Roster shapes. ESPN reports the lineup slot a player occupies, which is what
# the hub renders, so the slot list defines both roster size and composition.
_FOOTBALL_STARTERS = ("QB", "RB", "RB", "WR", "WR", "WR", "TE", "FLEX", "D/ST", "K")
_BASEBALL_BATTER_SLOTS = ("C", "1B", "2B", "3B", "SS", "OF", "OF", "OF", "UTIL", "DH")
_BASEBALL_PITCHER_SLOTS = ("SP", "SP", "SP", "SP", "RP", "RP", "RP")

_FLEX_POSITIONS = ("RB", "WR", "TE")
_FOOTBALL_BENCH_POSITIONS = ("QB", "RB", "RB", "WR", "WR", "TE", "K")
_BASEBALL_FIELD_POSITIONS = ("C", "1B", "2B", "3B", "SS", "OF")

# Mean season fantasy points by position, used as the centre of a wide normal.
_FOOTBALL_POINT_BASE = {"QB": 280.0, "RB": 170.0, "WR": 160.0, "TE": 110.0, "K": 120.0}
_DST_POINT_BASE = 105.0

# ESPN leaves injuryStatus unset for most players; a minority carry a real flag.
_INJURY_STATUSES = (
    None,
    None,
    None,
    None,
    None,
    None,
    "ACTIVE",
    "QUESTIONABLE",
    "DOUBTFUL",
    "OUT",
    "INJURY_RESERVE",
)

_ACQUISITION_TYPES = ("DRAFT", "ADD", "TRADE", "WAIVER")


class _Stub:
    """Attribute bag standing in for an espn-api object.

    ``sj.serialize`` reads league/team/player data purely via ``getattr``, so a
    plain namespace is enough to exercise the real serializer.
    """

    def __init__(self, **fields: Any) -> None:
        self.__dict__.update(fields)


def _person(rng: random.Random) -> str:
    return f"{rng.choice(_FIRST_NAMES)} {rng.choice(_LAST_NAMES)}"


def _percent_owned(rng: random.Random) -> float:
    # espn-api yields -1 when ESPN omits ownership. Emitting it occasionally
    # keeps that sentinel in front of the UI instead of hiding it.
    if rng.random() < 0.05:
        return -1.0
    return round(rng.uniform(0.1, 100.0), 1)


def _football_player(rng: random.Random, player_id: int, slot: str) -> _Stub:
    if slot == "FLEX":
        position = rng.choice(_FLEX_POSITIONS)
    elif slot == "BE":
        position = rng.choice(_FOOTBALL_BENCH_POSITIONS)
    else:
        position = slot

    if position == "D/ST":
        name = f"{rng.choice(_NFL_TEAMS)} D/ST"
        base = _DST_POINT_BASE
    else:
        name = _person(rng)
        base = _FOOTBALL_POINT_BASE[position]

    total = round(max(0.0, rng.gauss(base, base * 0.42)), 1)
    return _Stub(
        playerId=player_id,
        name=name,
        position=position,
        lineupSlot=slot,
        proTeam=rng.choice(_NFL_TEAMS),
        injuryStatus=rng.choice(_INJURY_STATUSES),
        status="ACTIVE",
        injured=rng.random() < 0.09,
        eligibleSlots=[position, "BE", "IR"],
        acquisitionType=rng.choice(_ACQUISITION_TYPES),
        percent_owned=_percent_owned(rng),
        total_points=total,
        projected_total_points=round(total * rng.uniform(0.75, 1.3), 1),
        avg_points=round(total / 17.0, 1),
    )


def _baseball_player(rng: random.Random, player_id: int, slot: str) -> _Stub:
    if slot in {"SP", "RP"}:
        pitcher = True
    elif slot in {"BE", "IL"}:
        pitcher = rng.random() < 0.45
    else:
        pitcher = False

    if slot in {"BE", "IL", "UTIL", "DH"}:
        position = (
            rng.choice(("SP", "RP")) if pitcher else rng.choice(_BASEBALL_FIELD_POSITIONS)
        )
    else:
        position = slot

    if pitcher:
        outs = rng.randint(60, 620)
        breakdown = {
            "W": float(rng.randint(0, 18)),
            "L": float(rng.randint(0, 14)),
            "SV": float(rng.randint(0, 38)),
            "HLD": float(rng.randint(0, 30)),
            "QS": float(rng.randint(0, 24)),
            "K": float(rng.randint(20, 250)),
            "ERA": round(rng.uniform(2.05, 5.85), 2),
            "WHIP": round(rng.uniform(0.92, 1.62), 2),
            # IP is intentionally omitted: the serializer derives it from OUTS.
            "OUTS": float(outs),
        }
        total = round(max(0.0, rng.gauss(420.0, 190.0)), 1)
    else:
        at_bats = rng.randint(120, 640)
        hits = int(at_bats * rng.uniform(0.19, 0.32))
        breakdown = {
            "AB": float(at_bats),
            "H": float(hits),
            "R": float(rng.randint(10, 118)),
            "HR": float(rng.randint(0, 47)),
            "RBI": float(rng.randint(8, 128)),
            "SB": float(rng.randint(0, 62)),
            "AVG": round(hits / at_bats, 3),
            "OBP": round(rng.uniform(0.275, 0.415), 3),
            "OPS": round(rng.uniform(0.610, 1.045), 3),
        }
        total = round(max(0.0, rng.gauss(480.0, 210.0)), 1)

    return _Stub(
        playerId=player_id,
        name=_person(rng),
        position=position,
        lineupSlot=slot,
        proTeam=rng.choice(_MLB_TEAMS),
        injuryStatus=rng.choice(_INJURY_STATUSES),
        status="ACTIVE",
        injured=rng.random() < 0.11,
        eligibleSlots=[position, "BE", "IL"],
        acquisitionType=rng.choice(_ACQUISITION_TYPES),
        percent_owned=_percent_owned(rng),
        total_points=total,
        projected_total_points=round(total * rng.uniform(0.8, 1.25), 1),
        avg_points=round(total / 26.0, 1),
        stats={0: {"breakdown": breakdown}},
    )


def _roster_slots(spec: LeagueSpec) -> tuple[str, ...]:
    """Lineup slots for one team, widened for dynasty formats."""
    if spec.sport == "baseball":
        bench = ("BE",) * (10 if spec.format == "dynasty" else 6)
        return _BASEBALL_BATTER_SLOTS + _BASEBALL_PITCHER_SLOTS + bench + ("IL", "IL")
    bench = ("BE",) * (12 if spec.format == "dynasty" else 6)
    return _FOOTBALL_STARTERS + bench


def _team_names(spec: LeagueSpec, count: int) -> list[str]:
    pool = _BASEBALL_TEAM_NAMES if spec.sport == "baseball" else _FOOTBALL_TEAM_NAMES
    if count <= len(pool):
        return list(pool[:count])
    # More teams than names: suffix the wrapped entries so names stay unique.
    return [
        pool[i % len(pool)] if i < len(pool) else f"{pool[i % len(pool)]} {i // len(pool) + 1}"
        for i in range(count)
    ]


def _build_team(
    spec: LeagueSpec,
    rng: random.Random,
    *,
    team_index: int,
    name: str,
    first_player_id: int,
    games: int,
) -> _Stub:
    make_player = _baseball_player if spec.sport == "baseball" else _football_player
    roster = [
        make_player(rng, first_player_id + offset, slot)
        for offset, slot in enumerate(_roster_slots(spec))
    ]

    wins = rng.randint(0, games)
    owner = _person(rng).split()
    points_for: float | None = None
    if spec.sport == "football":
        # Starters drive scoring; bench points never count toward a team total.
        points_for = round(sum(p.total_points for p in roster[: len(_FOOTBALL_STARTERS)]), 1)

    return _Stub(
        team_id=team_index + 1,
        team_name=name,
        team_abbrev="".join(word[0] for word in name.split())[:4].upper(),
        owners=[{"firstName": owner[0], "lastName": owner[-1]}],
        logo_url=None,
        wins=wins,
        losses=games - wins,
        ties=0,
        # Baseball leaves points_for unset on the ESPN team object; leaving it
        # None here exercises the serializer's roster-sum fallback.
        points_for=points_for,
        points_against=(
            round(points_for * rng.uniform(0.82, 1.18), 1) if points_for is not None else None
        ),
        standing=None,
        division_name=rng.choice(("East", "West")),
        roster=roster,
    )


def sample_league(
    spec: LeagueSpec,
    season: int,
    *,
    teams: int = DEFAULT_TEAM_COUNT,
) -> _Stub:
    """Build one deterministic espn-api-shaped league object."""
    if teams < 2:
        raise ValueError("teams must be at least 2")

    rng = random.Random(f"{spec.id}:{season}")
    games = 14 if spec.sport == "football" else 24
    names = _team_names(spec, teams)

    built = [
        _build_team(
            spec,
            rng,
            team_index=index,
            name=names[index],
            # Season-scoped ids keep players distinct across league-seasons.
            first_player_id=season * 100_000 + index * 100 + 1,
            games=games,
        )
        for index in range(teams)
    ]

    # Schedule / scores / outcomes mirror what espn-api already attaches after
    # the mMatchup fetch. Draft mirrors league.draft from mDraftDetail. Both are
    # free data the live serializer now persists (roadmap 2.1).
    _assign_matchups(built, games=games, rng=rng)
    # Random pre-matchup W/L must not disagree with the schedule tape.
    _reconcile_records_from_matchups(built)

    # Standings by win pct then points, matching how ESPN orders a league.
    ranked = sorted(
        built,
        key=lambda team: (
            -(team.wins + 0.5 * getattr(team, "ties", 0)),
            -(team.points_for or 0.0),
        ),
    )
    for place, team in enumerate(ranked, start=1):
        team.standing = place

    draft = _build_draft(built, rounds=3)
    # Settings (from mSettings) + recent_activity + free_agents (roadmap 2.4).
    settings = _build_settings(spec, teams=teams, games=games)
    activities = _build_activities(built, season=season, rng=rng)
    agents = _build_free_agents(spec, season=season, rng=rng)

    def recent_activity(
        size: int = 25,
        msg_type: str | None = None,
        offset: int = 0,
    ) -> list[_Stub]:
        del msg_type
        return activities[offset : offset + size]

    def free_agents(
        week: int | None = None,
        size: int = 50,
        position: str | None = None,
        position_id: int | None = None,
    ) -> list[_Stub]:
        del week, position, position_id
        return agents[:size]

    return _Stub(
        settings=settings,
        teams=built,
        current_week=games,
        draft=draft,
        year=season,
        recent_activity=recent_activity,
        free_agents=free_agents,
    )


def _build_settings(spec: LeagueSpec, *, teams: int, games: int) -> _Stub:
    dynasty = spec.format == "dynasty"
    return _Stub(
        name=spec.name,
        scoring_type="H2H_CATEGORY" if spec.sport == "baseball" else "H2H_POINTS",
        reg_season_count=games,
        playoff_team_count=4 if teams >= 6 else max(2, teams // 2),
        playoff_matchup_period_length=1,
        playoff_seed_tie_rule="TOTAL_POINTS_SCORED",
        playoff_tie_rule="NONE",
        tie_rule="NONE",
        keeper_count=5 if dynasty else 0,
        faab=True,
        acquisition_budget=200 if dynasty else 100,
        veto_votes_required=4,
        trade_deadline=max(1, games - 2),
        team_count=teams,
        median_scoring=False,
        division_map={"0": "East", "1": "West"} if teams >= 8 else {},
        position_slot_counts=(
            {"QB": 1, "RB": 2, "WR": 2, "TE": 1, "FLEX": 1, "DST": 1, "K": 1, "BE": 6}
            if spec.sport == "football"
            else None
        ),
        scoring_format=(
            [
                {"id": 3, "abbr": "PTD", "label": "Passing TD", "points": 4.0},
                {"id": 24, "abbr": "RTD", "label": "Rushing TD", "points": 6.0},
            ]
            if spec.sport == "football"
            else None
        ),
    )


def _build_activities(
    teams: list[_Stub], *, season: int, rng: random.Random
) -> list[_Stub]:
    """Fabricate a small FA add/drop + trade board for seed snapshots."""
    if season < 2019 or len(teams) < 2:
        return []
    t0, t1 = teams[0], teams[1]
    p0 = t0.roster[0]
    p1 = t1.roster[0]
    # Dates as epoch-ms strings matching espn-api Activity.date.
    base = int(f"{season}0901000000")
    return [
        _Stub(
            date=str(base),
            actions=[(t0, "FA ADDED", p0, 12.0)],
        ),
        _Stub(
            date=str(base + 86_400_000),
            actions=[(t0, "DROPPED", p0, 0), (t1, "TRADED", p1, 0)],
        ),
        _Stub(
            date=str(base + 172_800_000),
            actions=[(t1, "FA ADDED", p1, 3.0)],
        ),
    ]


def _build_free_agents(
    spec: LeagueSpec, *, season: int, rng: random.Random, count: int = 20
) -> list[_Stub]:
    """Fabricate a size-capped FREEAGENT/WAIVERS pool (ids outside roster space)."""
    if season < 2019:
        return []
    agents: list[_Stub] = []
    for index in range(count):
        # Keep ids far from roster ids (season * 1000 + …) used by sample_league.
        player_id = season * 100_000 + 50_000 + index
        if spec.sport == "baseball":
            slot = rng.choice(("OF", "1B", "SP", "RP", "UTIL"))
            player = _baseball_player(rng, player_id, slot)
        else:
            slot = rng.choice(("QB", "RB", "WR", "TE", "D/ST", "K"))
            player = _football_player(rng, player_id, slot)
        player.lineupSlot = "FA"
        player.slot_position = "FA"
        player.status = "FREEAGENT" if index % 3 else "WAIVERS"
        agents.append(player)
    return agents


def _assign_matchups(teams: list[_Stub], *, games: int, rng: random.Random) -> None:
    """Fill parallel schedule/scores/outcomes arrays on every team stub."""
    by_id = {team.team_id: team for team in teams}
    ids = list(by_id)
    n = len(ids)
    for team in teams:
        team.schedule = []
        team.scores = []
        team.outcomes = []

    if n < 2:
        return

    for week in range(games):
        # Circle method: fix one team, rotate the rest, pair ends.
        rotation = week % (n - 1)
        ordered = ids[0:1] + ids[1:][rotation:] + ids[1:][:rotation]
        paired: set[int] = set()
        week_results: dict[int, tuple[int, float, str]] = {}
        for i in range(n // 2):
            home_id = ordered[i]
            away_id = ordered[n - 1 - i]
            home_score = round(rng.uniform(70.0, 160.0), 1)
            away_score = round(rng.uniform(70.0, 160.0), 1)
            if home_score > away_score:
                home_out, away_out = "W", "L"
            elif home_score < away_score:
                home_out, away_out = "L", "W"
            else:
                home_out, away_out = "T", "T"
            week_results[home_id] = (away_id, home_score, home_out)
            week_results[away_id] = (home_id, away_score, away_out)
            paired.add(home_id)
            paired.add(away_id)

        for team_id, team in by_id.items():
            if team_id in week_results:
                opponent, score, outcome = week_results[team_id]
                team.schedule.append(opponent)
                team.scores.append(score)
                team.outcomes.append(outcome)
            else:
                # Bye week — espn-api sets opponent id to self and outcome U.
                team.schedule.append(team_id)
                team.scores.append(0.0)
                team.outcomes.append("U")


def _reconcile_records_from_matchups(teams: list[_Stub]) -> None:
    """Set wins / losses / ties / points_for from schedule outcomes.

    ``_build_team`` picks a random record before matchups exist; after
    ``_assign_matchups`` the tape is authoritative. Bye weeks (outcome ``U``,
    opponent == self) do not count in the record. Football ``points_for`` is
    the sum of non-bye scores so it matches the schedule board.
    """
    for team in teams:
        wins = losses = ties = 0
        points = 0.0
        schedule = getattr(team, "schedule", None) or []
        scores = getattr(team, "scores", None) or []
        outcomes = getattr(team, "outcomes", None) or []
        for i, outcome in enumerate(outcomes):
            opp = schedule[i] if i < len(schedule) else team.team_id
            if opp == team.team_id:
                continue
            if outcome == "W":
                wins += 1
            elif outcome == "L":
                losses += 1
            elif outcome == "T":
                ties += 1
            if i < len(scores) and scores[i] is not None:
                points += float(scores[i])
        team.wins = wins
        team.losses = losses
        team.ties = ties
        if hasattr(team, "points_for") and team.points_for is not None:
            # Football stubs set points_for; baseball leaves it None for the
            # serializer's roster-sum fallback — preserve that.
            team.points_for = round(points, 1)


def _build_draft(teams: list[_Stub], *, rounds: int = 3) -> list[_Stub]:
    """Snake-draft the first roster players so seed snapshots carry a draft board."""
    order = [team.team_id for team in teams]
    by_id = {team.team_id: team for team in teams}
    picks: list[_Stub] = []
    for rnd in range(1, rounds + 1):
        round_order = order if rnd % 2 == 1 else list(reversed(order))
        for pick_num, team_id in enumerate(round_order, start=1):
            team = by_id[team_id]
            player = team.roster[(rnd - 1) % len(team.roster)]
            picks.append(
                _Stub(
                    team=team,
                    playerId=player.playerId,
                    playerName=player.name,
                    round_num=rnd,
                    round_pick=pick_num,
                    bid_amount=0,
                    keeper_status=False,
                    nominatingTeam=None,
                )
            )
    return picks


def sample_snapshot(
    spec: LeagueSpec,
    season: int,
    *,
    teams: int = DEFAULT_TEAM_COUNT,
) -> dict[str, Any]:
    """Build one synthetic snapshot in the live sync's exact schema."""
    return build_snapshot(sample_league(spec, season, teams=teams), spec, season)


def seed_store(
    *,
    league_ids: list[str] | None = None,
    seasons: list[int] | None = None,
    current_only: bool = False,
    teams: int = DEFAULT_TEAM_COUNT,
    registry_path: Path | str | None = None,
    store_dir: Path | str | None = None,
    force: bool = False,
    on_event: Any = None,
) -> list[tuple[str, int, str]]:
    """Write synthetic snapshots for the selected leagues and seasons.

    Always targets a local directory; ``SJ_GCS_BUCKET`` is ignored so seeded
    data can never reach the production bucket. Refuses to write into a store
    that already holds real snapshots unless ``force`` is set.
    """
    registry = load_registry(registry_path)
    selected = registry.leagues
    if league_ids:
        wanted = set(league_ids)
        selected = [lg for lg in selected if lg.id in wanted]
        missing = wanted - {lg.id for lg in selected}
        if missing:
            raise KeyError(f"Unknown league id(s): {sorted(missing)}")

    root = Path(store_dir) if store_dir is not None else DEFAULT_STORE_DIR
    if not force and _has_real_snapshots(root):
        raise RuntimeError(
            f"{root} already contains snapshots without a {MARKER_NAME} marker; "
            "these may be real league data. Re-run with --force to overwrite."
        )

    def emit(message: str) -> None:
        if on_event is not None:
            on_event(message)

    root.mkdir(parents=True, exist_ok=True)
    (root / MARKER_NAME).write_text(MARKER_TEXT, encoding="utf-8")

    store = FileStore(root)
    written: list[tuple[str, int, str]] = []
    for spec in selected:
        target_seasons = [spec.current_season] if current_only else list(spec.seasons)
        if seasons is not None:
            target_seasons = [s for s in target_seasons if s in seasons]
        for season in target_seasons:
            snapshot = sample_snapshot(spec, season, teams=teams)
            location = store.write(snapshot)
            written.append((spec.id, season, location))
            emit(
                f"seeded {spec.id} {season} "
                f"({snapshot['team_count']} teams, {len(snapshot['players'])} players)"
            )
    return written


def _has_real_snapshots(root: Path) -> bool:
    """True when ``root`` holds snapshots that `sj seed` did not write."""
    if not root.exists() or (root / MARKER_NAME).exists():
        return False
    # v1 monoliths or v2 manifests both count as existing snapshot data.
    if any(path.name != INDEX_NAME for path in root.glob("*/*.json")):
        return True
    return any(root.glob("*/*/manifest.json"))
